[project]
name = "hyperliquid-info-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "hyperliquid-python-sdk>=0.15.0",
    "iso8601>=2.1.0",
    "mcp[cli]>=1.9.1",
    "pillow>=11.2.1",
]
